version: 2.1

orbs:
  matlab: mathworks/matlab@1

workflows:
  build-workflow:
    jobs:
      - build

jobs:
  build:
    machine: true
    resource_class: sameagen-mw/linux
    steps:
    #  - run: # Linux agent
    #       name: Add MATLAB to path
    #       command: |
    #         echo 'export PATH=/path/to/MATLAB/bin:"$PATH"' >> "$BASH_ENV"
    #         source "$BASH_ENV"
    # - run: # mac agent
    #     name: Add MATLAB to path
    #     command: |
    #       echo 'export PATH=/path/to/MATLAB.app/bin:"$PATH"' >> "$BASH_ENV"
    #       source "$BASH_ENV"
      - run: # windows agent
          name: Add MATLAB to path
          shell: powershell.exe
          command: |
            echo "hello world"
            # echo $BASH_ENV
            # echo 'export PATH="C:\Program Files\MATLAB\R2023b\bin":"$PATH"' >> "$BASH_ENV"
            # source "$BASH_ENV"
            echo "goodbye"
      - matlab/run-command:
          command: ver